# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: parse.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='parse.proto',
  package='parser',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0bparse.proto\x12\x06parser\"\x1f\n\x0cParseRequest\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\"\x1c\n\nParseReply\x12\x0e\n\x06result\x18\x01 \x01(\t2=\n\x06Parser\x12\x33\n\x05Parse\x12\x14.parser.ParseRequest\x1a\x12.parser.ParseReply\"\x00\x62\x06proto3'
)




_PARSEREQUEST = _descriptor.Descriptor(
  name='ParseRequest',
  full_name='parser.ParseRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='content', full_name='parser.ParseRequest.content', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=54,
)


_PARSEREPLY = _descriptor.Descriptor(
  name='ParseReply',
  full_name='parser.ParseReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='parser.ParseReply.result', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=84,
)

DESCRIPTOR.message_types_by_name['ParseRequest'] = _PARSEREQUEST
DESCRIPTOR.message_types_by_name['ParseReply'] = _PARSEREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ParseRequest = _reflection.GeneratedProtocolMessageType('ParseRequest', (_message.Message,), {
  'DESCRIPTOR' : _PARSEREQUEST,
  '__module__' : 'parse_pb2'
  # @@protoc_insertion_point(class_scope:parser.ParseRequest)
  })
_sym_db.RegisterMessage(ParseRequest)

ParseReply = _reflection.GeneratedProtocolMessageType('ParseReply', (_message.Message,), {
  'DESCRIPTOR' : _PARSEREPLY,
  '__module__' : 'parse_pb2'
  # @@protoc_insertion_point(class_scope:parser.ParseReply)
  })
_sym_db.RegisterMessage(ParseReply)



_PARSER = _descriptor.ServiceDescriptor(
  name='Parser',
  full_name='parser.Parser',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=86,
  serialized_end=147,
  methods=[
  _descriptor.MethodDescriptor(
    name='Parse',
    full_name='parser.Parser.Parse',
    index=0,
    containing_service=None,
    input_type=_PARSEREQUEST,
    output_type=_PARSEREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_PARSER)

DESCRIPTOR.services_by_name['Parser'] = _PARSER

# @@protoc_insertion_point(module_scope)
